version: 1.0.{build}

environment:
  CAKE_SETTINGS_SKIPVERIFICATION: true
  CAKE_NUGET_USEINPROCESSCLIENT: true

image:
  - Visual Studio 2017
  - Ubuntu
init:
  - ps: >-
      Install-Module Pester -Force -Scope CurrentUser;

      pwsh -command "Install-Module Pester -Force -Scope CurrentUser";
build_script:
  - ps: >-
      Write-Output "nothing to build."

test_script:
  - ps: >-
      Invoke-Expression .\tests\Tests.ps1

artifacts:
  - path: '**\*'
    name: Resources
